### ISSUE TITLE
post install error, but only on fresh install

### ISSUE THREAD

**Issue by Zorrototo** [OpenGamePanel/OGP-Website#42]
I noticed on reinstalling an Avorion Linux 64 server that there is an error on post install.

```
Success! App '565060' fully installed.
[1mexit
[0m./postinstall.sh: line 8: 1: command not found
```

If I go again on same server and click Install/Update button, the error does not show then. This error only appear on first install, not when updating over.

**Comment by Zorrototo** [comment]
I have to add that the post install script itself worked as intended though, .so file copied, and start script created, server starts successfully.

**Comment by own3mall** [comment]
To troubleshoot this further and to help me out, can you please try the following:

Remove this line and the two other rm lines beneath it:

https://github.com/OpenGamePanel/OGP-Agent-Linux/blob/master/ogp_agent.pl#L1885
https://github.com/OpenGamePanel/OGP-Agent-Linux/blob/master/ogp_agent.pl#L1886
https://github.com/OpenGamePanel/OGP-Agent-Linux/blob/master/ogp_agent.pl#L1887

Run it again so that you run into the problem.  After, post the contents of the script in the {OGP_AGENT_DIR}/tmp/home_id/postinstall.sh

**Comment by Zorrototo** [comment]
Here it is (without my sudo password :D):

`cd '/home/ogp_agent/OGP_User_Files/57'

cp linux64/steamclient.so ./steamclient.so
echo '#!/bin/bash
./bin/AvorionServer $@' > avorion_ogpstarter.sh
chmod +x avorion_ogpstarter.sh
 
1
cd '/home/ogp_agent/OGP_User_Files/57'
echo 'blablibloop' | sudo -S -p "" bash secure.sh
rm -f secure.sh
cd '/usr/share/ogp_agent/tmp/home_id_57'
`

**Comment by Zorrototo** [comment]
If i run Install/update on same server here is what I have (no error):

```
cd '/home/ogp_agent/OGP_User_Files/57'

cp linux64/steamclient.so ./steamclient.so
echo '#!/bin/bash
./bin/AvorionServer $@' > avorion_ogpstarter.sh
chmod +x avorion_ogpstarter.sh
 
echo 'blablibloop' | sudo -S -p "" sh -c "chown -Rf 1001:1001 '/home/ogp_agent/OGP_User_Files/57/bin/AvorionServer' && chattr -Rf +i '/home/ogp_agent/OGP_User_Files/57/bin/AvorionServer'"
cd '/home/ogp_agent/OGP_User_Files/57'
echo 'blablibloop' | sudo -S -p "" bash secure.sh
rm -f secure.sh
cd '/usr/share/ogp_agent/tmp/home_id_57'
```

**Comment by own3mall** [comment]
Please try now.  It should be fixed.

**Comment by Zorrototo** [comment]
Yes it is fixed, no more error.

Something I noticed though, is that the files in <lock_files> are not locked on fresh install, only after updating again.

**Comment by own3mall** [comment]
That shouldn't be the case anymore.  Please re-verify.  My last fix should have addressed that too.  The commands no longer check to make sure the file exists.   They should be running appropriately and the files should exist when the command tries to run.

**Comment by Zorrototo** [comment]
Restarted agent, reinstalled fresh avorion server, and still the same. /bin/AvorionServer is not locked after install. Here is post install now:

```
cd '/home/ogp_agent/OGP_User_Files/62'

cp linux64/steamclient.so ./steamclient.so
echo '#!/bin/bash
./bin/AvorionServer $@' > avorion_ogpstarter.sh
chmod +x avorion_ogpstarter.sh
 
echo 'blablibloop' | sudo -S -p "" sh -c "-1" > /dev/null 2>&1
echo 'blablibloop' | sudo -S -p "" sh -c "-1" > /dev/null 2>&1
cd '/home/ogp_agent/OGP_User_Files/62'
echo 'blablibloop' | sudo -S -p "" bash secure.sh
cd '/usr/share/ogp_agent/tmp/home_id_62'
```

Here it is after I re-run the install/update over same fresh server:

```
cd '/home/ogp_agent/OGP_User_Files/62'

cp linux64/steamclient.so ./steamclient.so
echo '#!/bin/bash
./bin/AvorionServer $@' > avorion_ogpstarter.sh
chmod +x avorion_ogpstarter.sh
 
echo 'blablibloop' | sudo -S -p "" sh -c "chown -Rf 1001:1001 '/home/ogp_agent/OGP_User_Files/62/bin/AvorionServer' && chattr -Rf +i '/home/ogp_agent/OGP_User_Files/62/bin/AvorionServer'" > /dev/null 2>&1
echo 'blablibloop' | sudo -S -p "" sh -c "-1" > /dev/null 2>&1
cd '/home/ogp_agent/OGP_User_Files/62'
echo 'blablibloop' | sudo -S -p "" bash secure.sh
cd '/usr/share/ogp_agent/tmp/home_id_62'
```

Then now bin/AvorionServer is locked correctly.

**Comment by own3mall** [comment]
Try it now.

**Comment by Zorrototo** [comment]
Fixed :) thank you.
